import { Router } from "express";
import healthRoutes from "../../modules/health/health.routes";
import authRoutes from "../../modules/auth/auth.routes";
import usersRoutes from "../../modules/users/users.routes";
import sellerApplicationsRoutes from "../../modules/sellerApplications/sellerApplications.routes";
import adminSellerApplicationsRoutes from "../../modules/sellerApplications/admin/sellerApplications.admin.routes";
import storesRoutes from "../../modules/stores/stores.routes";
import categoriesRoutes from "../../modules/categories/categories.routes";
import adminCategoriesRoutes from "../../modules/categories/admin/categories.admin.routes";
import productsRoutes from "../../modules/products/products.routes";
import adminProductsRoutes from "../../modules/products/admin/products.admin.routes";
import marketplaceRoutes from "../../modules/marketplace/marketplace.routes";
import cartRoutes from "../../modules/cart/cart.routes";
import wishlistRoutes from "../../modules/wishlist/wishlist.routes";
import checkoutRoutes from "../../modules/checkout/checkout.routes";
import ordersRoutes from "../../modules/orders/orders.routes";
import sellerOrdersRoutes from "../../modules/orders/seller/sellerOrders.routes";
import entitlementsRoutes from "../../modules/entitlements/entitlements.routes";
import reviewsRoutes from "../../modules/reviews/reviews.routes";
import productReportsRoutes from "../../modules/productReports/productReports.routes";
import adminProductReportsRoutes from "../../modules/productReports/admin/productReports.admin.routes";

const router = Router();

router.use("/health", healthRoutes);
router.use("/auth", authRoutes);
router.use("/users", usersRoutes);
router.use("/seller-applications", sellerApplicationsRoutes);
router.use("/admin/seller-applications", adminSellerApplicationsRoutes);
router.use("/stores", storesRoutes);
router.use("/categories", categoriesRoutes);
router.use("/admin/categories", adminCategoriesRoutes);
router.use("/products", productsRoutes);
router.use("/admin/products", adminProductsRoutes);
router.use("/marketplace", marketplaceRoutes);
router.use("/cart", cartRoutes);
router.use("/wishlist", wishlistRoutes);
router.use("/checkout", checkoutRoutes);
router.use("/orders", ordersRoutes);
router.use("/seller-orders", sellerOrdersRoutes);
router.use("/entitlements", entitlementsRoutes);
router.use("/reviews", reviewsRoutes);
router.use("/product-reports", productReportsRoutes);
router.use("/admin/product-reports", adminProductReportsRoutes);

export default router;
